def raise_exception():
 return 3+"3"
